language: ruby
cache: bundler
before_install:
  # rubygems 2.7.8 and greater include bundler
  - |
    rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
    if   [ "$rv" \< "2.3" ]; then gem update --system 2.7.10 --no-document
    elif [ "$rv" \< "2.7" ]; then gem update --system --no-document --conservative
    fi
  - ruby -v && gem --version && bundle version

addons:
  apt:
    packages:
      - libgmp-dev

after_failure:
  - "find . -name mkmf.log -exec cat {} \\;"

after_success:
  - "find . -name mkmf.log -exec cat {} \\;"

env:
  - USE_MINI_PORTILE=true
  - USE_MINI_PORTILE=false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - env: USE_MINI_PORTILE=false
