name: test suite
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  sqlite3:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2022"]
        ruby: ["3.1", "3.0", "2.7", "2.6"]
        lib: ["system", "packaged"]
        include:
          - os: "ubuntu-latest"
            ruby: "truffleruby-head"
            lib: "packaged"

          - os: "ubuntu-22.04"
            ruby: "head"
            lib: "packaged"

          - os: "ubuntu-22.04"
            ruby: "head"
            lib: "system"

          - os: "windows-2022"
            ruby: "ucrt"
            lib: "system"

          - os: "windows-2022"
            ruby: "mswin"
            lib: "system"

    runs-on: ${{matrix.os}}
    steps:
      - if: matrix.os == 'windows-2022'
        name: configure git crlf
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
          apt-get: "libsqlite3-dev"
          brew: "sqlite3"
          mingw: "sqlite3"
          vcpkg: "sqlite3"
      - if: matrix.lib == 'packaged'
        uses: actions/cache@v3
        with:
          path: ports
          key: ports-${{matrix.os}}-${{hashFiles('ext/sqlite3/extconf.rb')}}
      
      - run: bundle exec rake compile -- --disable-system-libraries
        if: matrix.lib == 'packaged'

      - run: bundle exec rake compile -- --enable-system-libraries
        if: matrix.lib == 'system' && !startsWith(matrix.os, 'macos')

      - run: bundle exec rake compile -- --enable-system-libraries --with-opt-dir=$(brew --prefix sqlite3)
        if: matrix.lib == 'system' && startsWith(matrix.os, 'macos')

      - run: bundle exec rake test

  old_sqlite3:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.5-buster # old enough to not support SQLITE_DBCONFIG_DQS_DDL
    steps:
      - uses: actions/checkout@v3
      - run: bundle install
      - run: bundle exec rake compile -- --enable-system-libraries
      - run: bundle exec rake test

  sqlcipher:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2022"]
        ruby: ["3.1", "2.6"] # oldest and newest
        include:
          - os: "windows-2022"
            ruby: "mingw"
          - os: "windows-2022"
            ruby: "mswin"
    runs-on: ${{matrix.os}}
    steps:
      - if: matrix.os == 'windows-2022'
        name: configure git crlf
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
          apt-get: "libsqlcipher-dev"
          brew: "sqlcipher"
          mingw: "sqlcipher"
          vcpkg: "sqlcipher"
      - run: bundle exec rake compile -- --with-sqlcipher
      - run: bundle exec rake test
