name: CI
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2022"]
        ruby: ["3.1", "3.0", "2.7", "2.6", "2.5"]
        include:
          - os: "ubuntu-latest"
            ruby: "truffleruby-head"
          - os: "ubuntu-latest"
            ruby: "head"
          - os: "windows-2022"
            ruby: "mingw"
    runs-on: ${{matrix.os}}
    steps:
      - if: matrix.os == 'windows-2022'
        name: configure git crlf
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: actions/checkout@v3
      - uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
          apt-get: "libsqlite3-dev"
          brew: "sqlite3"
          mingw: sqlite3

      - name: compile msys2
        run:  bundle exec rake compile:msys2
      - name: test
        run:  bundle exec rake test

  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.5-buster # old enough to not support SQLITE_DBCONFIG_DQS_DDL
    steps:
      - uses: actions/checkout@v3
      - run: bundle install
      - run: bundle exec rake compile
      - run: bundle exec rake test
